# Generated by Django 2.2 on 2022-04-26 03:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AriticlePost',
            new_name='ArticlePost',
        ),
    ]
